version: '3.8'

services:
  # PHP ve Apache Sunucusu
  php-server:
    image: php:7.4-apache
    container_name: ionic-backend
    ports:
      - "80:80"
    volumes:
      # Yerel backend klasörünü konteyner içindeki yapıya bağlar
      - ./backend:/var/www/html/ionCapImage
